using Rollbard.Library.Rollers.Interfaces;
using System.Collections.Generic;

namespace Rollbard.Library.Rollers
{
    public class JobRoller : FromListRoller<string>, IJobRoller
    {
        public JobRoller()
        {
            List = new List<string>
        {
            "Accountant",
            "Actor",
            "Acupuncturist",
            "Animal Trainer",
            "Arborist",
            "Archaeologist",
            "Architect",
            "Archivist",
            "Artist",
            "Assistant",
            "Astronomer",
            "Athlete",
            "Auctioneer",
            "Baker",
            "Banker",
            "Bartender",
            "Barber",
            "Blacksmith",
            "Bodyguard",
            "Bookkeeper",
            "Bounty Hunter",
            "Brewer",
            "Bricklayer",
            "Broadcaster",
            "Builder",
            "Bureaucrat",
            "Butcher",
            "Captain",
            "Caretaker",
            "Carpenter",
            "Cartographer",
            "Chemist",
            "Cleric",
            "Clerk",
            "Comedian",
            "Cook",
            "Courier",
            "Dancer",
            "Dishwasher",
            "Distiller",
            "Diver",
            "Doctor",
            "Dressmaker",
            "Driver",
            "Economist",
            "Engineer",
            "Entertainer",
            "Fisher",
            "Florist",
            "Gardener",
            "Gravedigger",
            "Guard",
            "Hacker",
            "Herbalist",
            "Housekeeper",
            "Innkeeper",
            "Interpreter",
            "Jeweler",
            "Journalist",
            "Judge",
            "Lawyer",
            "Librarian",
            "Locksmith",
            "Lumberjack",
            "Machinist",
            "Magistrate",
            "Mason",
            "Mercenary",
            "Merchant",
            "Midwife",
            "Miner",
            "Musician",
            "Nanny",
            "Nurse",
            "Operative",
            "Photographer",
            "Politician",
            "Roofer",
            "Sailor",
            "Samurai",
            "Scientist",
            "Sculptor",
            "Secretary",
            "Servant",
            "Shipwright",
            "Sheriff",
            "Singer",
            "Soldier",
            "Surgeon",
            "Tailor",
            "Tattooist",
            "Tax Collector",
            "Teacher",
            "Undertaker",
            "Warden",
            "Writer",
        };
        }

        public override List<string> List { get; }
    }
}